CREATE CONSTRAINT ON (node:`UNIQUE IMPORT LABEL`) ASSERT (node.`UNIQUE IMPORT ID`) IS UNIQUE;
UNWIND [{_id:0, properties:{title:"統治單位", parents:"***"}}, {_id:1, properties:{title:"土地", parents:"***"}}, {_id:2, properties:{title:"沒人擁有的區域", parents:"土地"}}, {_id:3, properties:{title:"統治單位擁有的區域", parents:"土地"}}, {_id:4, properties:{title:"物種", parents:"***"}}, {_id:5, properties:{title:"人類", parents:"物種"}}, {_id:6, properties:{title:"鳥類", parents:"物種"}}, {_id:7, properties:{title:"家族", parents:"統治單位"}}, {_id:8, properties:{title:"部落", parents:"統治單位"}}, {_id:9, properties:{title:"政府", parents:"統治單位"}}] AS row
CREATE (n:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row._id}) SET n += row.properties SET n:Category;
UNWIND [{_id:10, properties:{categories:"家族", title:"拉斯莫丁家族", url:"https://storyuniverse.fandom.com/zh-tw/wiki/%E6%8B%89%E6%96%AF%E8%8E%AB%E4%B8%81%E5%AE%B6%E6%97%8F"}}, {_id:11, properties:{categories:"家族", title:"亞歷山大家族", url:"https://storyuniverse.fandom.com/zh-tw/wiki/%E4%BA%9E%E6%AD%B7%E5%B1%B1%E5%A4%A7%E5%AE%B6%E6%97%8F"}}, {_id:12, properties:{categories:"家族", title:"西洛家族", url:"https://storyuniverse.fandom.com/zh-tw/wiki/%E8%A5%BF%E6%B4%9B%E5%AE%B6%E6%97%8F"}}, {_id:13, properties:{categories:"家族", title:"安拉斯托家族", url:"https://storyuniverse.fandom.com/zh-tw/wiki/%E5%AE%89%E6%8B%89%E6%96%AF%E6%89%98%E5%AE%B6%E6%97%8F"}}, {_id:14, properties:{categories:"家族", title:"吉里亞家族", url:"https://storyuniverse.fandom.com/zh-tw/wiki/%E5%90%89%E9%87%8C%E4%BA%9E%E5%AE%B6%E6%97%8F?venotify=created"}}, {_id:131, properties:{categories:"家族", title:"笞尼家族", url:"https://storyuniverse.fandom.com/zh-tw/wiki/%E7%AC%9E%E5%B0%BC%E5%AE%B6%E6%97%8F"}}] AS row
CREATE (n:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row._id}) SET n += row.properties SET n:家族;
UNWIND [{_id:128, properties:{categories:"政府", title:"馬爾獨中央政府", url:"https://storyuniverse.fandom.com/zh-tw/wiki/%E9%A6%AC%E7%88%BE%E7%8D%A8%E4%B8%AD%E5%A4%AE%E6%94%BF%E5%BA%9C"}}, {_id:129, properties:{categories:"政府", title:"芬喇地方政府", url:"https://storyuniverse.fandom.com/zh-tw/wiki/%E8%8A%AC%E5%96%87%E5%9C%B0%E6%96%B9%E6%94%BF%E5%BA%9C"}}, {_id:130, properties:{categories:"政府", title:"潤卡地方政府", url:"https://storyuniverse.fandom.com/zh-tw/wiki/%E6%BD%A4%E5%8D%A1%E5%9C%B0%E6%96%B9%E6%94%BF%E5%BA%9C"}}] AS row
CREATE (n:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row._id}) SET n += row.properties SET n:政府;
UNWIND [{_id:112, properties:{categories:"統治單位擁有的區域", title:"日惹", url:"https://storyuniverse.fandom.com/zh-tw/wiki/%E6%97%A5%E6%83%B9"}}, {_id:113, properties:{categories:"統治單位擁有的區域", title:"雙憂", url:"https://storyuniverse.fandom.com/zh-tw/wiki/%E9%9B%99%E6%86%82"}}, {_id:114, properties:{categories:"統治單位擁有的區域", title:"黎達", url:"https://storyuniverse.fandom.com/zh-tw/wiki/%E9%BB%8E%E9%81%94"}}, {_id:115, properties:{categories:"統治單位擁有的區域", title:"笞尼", url:"https://storyuniverse.fandom.com/zh-tw/wiki/%E7%AC%9E%E5%B0%BC"}}, {_id:116, properties:{categories:"統治單位擁有的區域", title:"圖拉瓦", url:"https://storyuniverse.fandom.com/zh-tw/wiki/%E5%9C%96%E6%8B%89%E7%93%A6"}}, {_id:117, properties:{categories:"統治單位擁有的區域", title:"宿笍", url:"https://storyuniverse.fandom.com/zh-tw/wiki/%E5%AE%BF%E7%AC%8D"}}, {_id:118, properties:{categories:"統治單位擁有的區域", title:"庫蝦", url:"https://storyuniverse.fandom.com/zh-tw/wiki/%E5%BA%AB%E8%9D%A6"}}, {_id:119, properties:{categories:"統治單位擁有的區域", title:"拉亥", url:"https://storyuniverse.fandom.com/zh-tw/wiki/%E6%8B%89%E4%BA%A5"}}, {_id:120, properties:{categories:"統治單位擁有的區域", title:"潤卡", url:"https://storyuniverse.fandom.com/zh-tw/wiki/%E6%BD%A4%E5%8D%A1"}}, {_id:121, properties:{categories:"統治單位擁有的區域", title:"烏達", url:"https://storyuniverse.fandom.com/zh-tw/wiki/%E7%83%8F%E9%81%94"}}, {_id:122, properties:{categories:"統治單位擁有的區域", title:"玫撒", url:"https://storyuniverse.fandom.com/zh-tw/wiki/%E7%8E%AB%E6%92%92"}}, {_id:123, properties:{categories:"統治單位擁有的區域", title:"芬喇", url:"https://storyuniverse.fandom.com/zh-tw/wiki/%E8%8A%AC%E5%96%87"}}, {_id:124, properties:{categories:"統治單位擁有的區域", title:"赫斯", url:"https://storyuniverse.fandom.com/zh-tw/wiki/%E8%B5%AB%E6%96%AF"}}, {_id:125, properties:{categories:"統治單位擁有的區域", title:"馬爾獨", url:"https://storyuniverse.fandom.com/zh-tw/wiki/%E9%A6%AC%E7%88%BE%E7%8D%A8"}}] AS row
CREATE (n:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row._id}) SET n += row.properties SET n:統治單位擁有的區域;
UNWIND [{_id:132, properties:{categories:"部落", title:"庫蝦部落", url:"https://storyuniverse.fandom.com/zh-tw/wiki/%E5%BA%AB%E8%9D%A6%E9%83%A8%E8%90%BD"}}, {_id:133, properties:{categories:"部落", title:"玫撒部落", url:"https://storyuniverse.fandom.com/zh-tw/wiki/%E7%8E%AB%E6%92%92%E9%83%A8%E8%90%BD"}}, {_id:134, properties:{categories:"部落", title:"宿笍部落", url:"https://storyuniverse.fandom.com/zh-tw/wiki/%E5%AE%BF%E7%AC%8D%E9%83%A8%E8%90%BD"}}] AS row
CREATE (n:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row._id}) SET n += row.properties SET n:部落;
UNWIND [{_id:135, properties:{gender:"生理女性", categories:"鳥類", title:"萊娜", url:"https://storyuniverse.fandom.com/zh-tw/wiki/%E8%90%8A%E5%A8%9C"}}] AS row
CREATE (n:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row._id}) SET n += row.properties SET n:鳥類;
UNWIND [{_id:15, properties:{gender:"生理女性", categories:"人類", title:"咪雅·比韋斯", url:"https://storyuniverse.fandom.com/zh-tw/wiki/%E5%92%AA%E9%9B%85%C2%B7%E6%AF%94%E9%9F%8B%E6%96%AF"}}, {_id:16, properties:{gender:"生理女性", categories:"人類", title:"薩里塔·基思", url:"https://storyuniverse.fandom.com/zh-tw/wiki/%E8%96%A9%E9%87%8C%E5%A1%94%C2%B7%E5%9F%BA%E6%80%9D"}}, {_id:17, properties:{gender:"生理女性", categories:"人類", title:"珍妮·特勒", url:"https://storyuniverse.fandom.com/zh-tw/wiki/%E7%8F%8D%E5%A6%AE%C2%B7%E7%89%B9%E5%8B%92"}}, {_id:18, properties:{gender:"生理女性", categories:"人類", title:"帕梅拉·麥克尼爾", url:"https://storyuniverse.fandom.com/zh-tw/wiki/%E5%B8%95%E6%A2%85%E6%8B%89%C2%B7%E9%BA%A5%E5%85%8B%E5%B0%BC%E7%88%BE"}}, {_id:19, properties:{gender:"生理女性", categories:"人類", title:"希樂里·貝茨"}}, {_id:20, properties:{gender:"生理女性", categories:"人類", title:"維維安·梅里克"}}, {_id:21, properties:{gender:"生理女性", categories:"人類", title:"莎拉·派克"}}, {_id:22, properties:{gender:"生理女性", categories:"人類", title:"艾米莉·威瑪"}}, {_id:23, properties:{gender:"生理女性", categories:"人類", title:"蘇菲·勞特納"}}, {_id:24, properties:{gender:"生理女性", categories:"人類", title:"瑪麗亞·曼特爾"}}, {_id:25, properties:{gender:"生理女性", categories:"人類", title:"米妮·克萊爾"}}, {_id:26, properties:{gender:"生理女性", categories:"人類", title:"伊蓮·墨里根"}}, {_id:27, properties:{gender:"生理女性", categories:"人類", title:"布里亞娜·漢普登"}}, {_id:35, properties:{gender:"生理女性", categories:"人類", title:"塞拉利昂·貝茨"}}, {_id:36, properties:{gender:"生理女性", categories:"人類", title:"露西·裡佩頓"}}, {_id:37, properties:{gender:"生理女性", categories:"人類", title:"瑪麗·海格爾"}}, {_id:38, properties:{gender:"生理女性", categories:"人類", title:"凱拉·哈德克"}}, {_id:39, properties:{gender:"生理女性", categories:"人類", title:"索尼亞·班克斯"}}, {_id:40, properties:{gender:"生理女性", categories:"人類", title:"戴西·傑克遜"}}, {_id:41, properties:{gender:"生理女性", categories:"人類", title:"娜迪亞·柯林斯"}}] AS row
CREATE (n:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row._id}) SET n += row.properties SET n:人類;
UNWIND [{_id:42, properties:{gender:"生理女性", categories:"人類", title:"薩拉·吉里亞", url:"https://storyuniverse.fandom.com/zh-tw/wiki/%E8%96%A9%E6%8B%89%C2%B7%E5%90%89%E9%87%8C%E4%BA%9E"}}, {_id:43, properties:{gender:"生理女性", categories:"人類", title:"梅蘭妮·吉里亞"}}, {_id:44, properties:{gender:"生理女性", categories:"人類", title:"凡妮莎·吉里亞"}}, {_id:45, properties:{gender:"生理女性", categories:"人類", title:"戴西·安拉斯托", url:"https://storyuniverse.fandom.com/zh-tw/wiki/%E6%88%B4%E8%A5%BF%C2%B7%E5%AE%89%E6%8B%89%E6%96%AF%E6%89%98"}}, {_id:46, properties:{gender:"生理女性", categories:"人類", title:"瑪姬·安拉斯托"}}, {_id:47, properties:{gender:"生理女性", categories:"人類", title:"拉克希米·安拉斯托"}}, {_id:48, properties:{gender:"生理女性", categories:"人類", title:"海利·安拉斯托"}}, {_id:49, properties:{gender:"生理女性", categories:"人類", title:"凱瑟琳·玫撒", url:"https://storyuniverse.fandom.com/zh-tw/wiki/%E5%87%B1%E7%91%9F%E7%90%B3%C2%B7%E7%8E%AB%E6%92%92"}}, {_id:50, properties:{gender:"生理女性", categories:"人類", title:"伊莎貝拉·玫撒"}}, {_id:51, properties:{gender:"生理女性", categories:"人類", title:"黛安·玫撒"}}, {_id:52, properties:{gender:"生理女性", categories:"人類", title:"阿里安娜·庫蝦", url:"https://storyuniverse.fandom.com/zh-tw/wiki/%E9%98%BF%E9%87%8C%E5%AE%89%E5%A8%9C%C2%B7%E5%BA%AB%E8%9D%A6"}}, {_id:53, properties:{gender:"生理女性", categories:"人類", title:"琪亞拉·庫蝦"}}, {_id:54, properties:{gender:"生理女性", categories:"人類", title:"加布里埃拉·庫蝦"}}, {_id:55, properties:{gender:"生理女性", categories:"人類", title:"阿里安娜·宿笍", url:"https://storyuniverse.fandom.com/zh-tw/wiki/%E9%98%BF%E9%87%8C%E5%AE%89%E5%A8%9C%C2%B7%E5%AE%BF%E7%AC%8D"}}, {_id:56, properties:{gender:"生理女性", categories:"人類", title:"琳達·宿笍"}}, {_id:57, properties:{gender:"生理女性", categories:"人類", title:"莱拉·宿笍"}}, {_id:58, properties:{gender:"生理女性", categories:"人類", title:"塞拉利昂·笞尼", url:"https://storyuniverse.fandom.com/zh-tw/wiki/%E5%A1%9E%E6%8B%89%E5%88%A9%E6%98%82%C2%B7%E7%AC%9E%E5%B0%BC"}}, {_id:59, properties:{gender:"生理女性", categories:"人類", title:"萊拉尼·笞尼"}}, {_id:60, properties:{gender:"生理男性", categories:"人類", title:"安東尼奧·巴克利", url:"https://storyuniverse.fandom.com/zh-tw/wiki/%E5%AE%89%E6%9D%B1%E5%B0%BC%E5%A5%A7%C2%B7%E5%B7%B4%E5%85%8B%E5%88%A9"}}, {_id:61, properties:{gender:"生理男性", categories:"人類", title:"盧克·布萊德爾", url:"https://storyuniverse.fandom.com/zh-tw/wiki/%E7%9B%A7%E5%85%8B%C2%B7%E5%B8%83%E8%90%8A%E5%BE%B7%E7%88%BE"}}] AS row
CREATE (n:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row._id}) SET n += row.properties SET n:人類;
UNWIND [{_id:62, properties:{gender:"生理男性", categories:"人類", title:"懷亞特·斯特拉", url:"https://storyuniverse.fandom.com/zh-tw/wiki/%E6%87%B7%E4%BA%9E%E7%89%B9%C2%B7%E6%96%AF%E7%89%B9%E6%8B%89"}}, {_id:63, properties:{gender:"生理男性", categories:"人類", title:"布蘭登·威瑪", url:"https://storyuniverse.fandom.com/zh-tw/wiki/%E5%B8%83%E8%98%AD%E7%99%BB%C2%B7%E5%A8%81%E7%91%AA"}}, {_id:64, properties:{gender:"生理男性", categories:"人類", title:"亨特·哈里斯"}}, {_id:65, properties:{gender:"生理男性", categories:"人類", title:"達克斯頓·布魯克斯"}}, {_id:66, properties:{gender:"生理男性", categories:"人類", title:"安迪·貝文"}}, {_id:67, properties:{gender:"生理男性", categories:"人類", title:"埃迪·馬利"}}, {_id:68, properties:{gender:"生理男性", categories:"人類", title:"萊德·丁威迪"}}, {_id:69, properties:{gender:"生理男性", categories:"人類", title:"特倫特·博爾頓"}}, {_id:70, properties:{gender:"生理男性", categories:"人類", title:"帕維爾·海格爾"}}, {_id:71, properties:{gender:"生理男性", categories:"人類", title:"克里斯多夫·斯特林"}}, {_id:72, properties:{gender:"生理男性", categories:"人類", title:"達米安·克拉克"}}, {_id:73, properties:{gender:"生理男性", categories:"人類", title:"克林特·嘿默"}}, {_id:74, properties:{gender:"生理男性", categories:"人類", title:"布萊克·勞森"}}, {_id:75, properties:{gender:"生理男性", categories:"人類", title:"特雷弗·斯皮爾伯格"}}, {_id:76, properties:{gender:"生理男性", categories:"人類", title:"梅森·辛納屈"}}, {_id:77, properties:{gender:"生理男性", categories:"人類", title:"奧伯利·庫柏力克"}}, {_id:78, properties:{gender:"生理男性", categories:"人類", title:"阿爾弗雷多·麥亞當斯"}}, {_id:79, properties:{gender:"生理男性", categories:"人類", title:"克里斯多夫·吉里亞", url:"https://storyuniverse.fandom.com/zh-tw/wiki/%E5%85%8B%E9%87%8C%E6%96%AF%E5%A4%9A%E5%A4%AB%C2%B7%E5%90%89%E9%87%8C%E4%BA%9E"}}, {_id:80, properties:{gender:"生理男性", categories:"人類", title:"達克斯頓·吉里亞"}}, {_id:81, properties:{gender:"生理男性", categories:"人類", title:"以賽亞·吉里亞"}}] AS row
CREATE (n:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row._id}) SET n += row.properties SET n:人類;
UNWIND [{_id:82, properties:{gender:"生理男性", categories:"人類", title:"達米安·安拉斯托", url:"https://storyuniverse.fandom.com/zh-tw/wiki/%E9%81%94%E7%B1%B3%E5%AE%89%C2%B7%E5%AE%89%E6%8B%89%E6%96%AF%E6%89%98"}}, {_id:83, properties:{gender:"生理男性", categories:"人類", title:"亞當·安拉斯托"}}, {_id:84, properties:{gender:"生理男性", categories:"人類", title:"肯尼·玫撒", url:"https://storyuniverse.fandom.com/zh-tw/wiki/%E8%82%AF%E5%B0%BC%C2%B7%E7%8E%AB%E6%92%92"}}, {_id:85, properties:{gender:"生理男性", categories:"人類", title:"海斯·玫撒"}}, {_id:86, properties:{gender:"生理男性", categories:"人類", title:"斯凱勒·玫撒"}}, {_id:87, properties:{gender:"生理男性", categories:"人類", title:"多里安·庫蝦", url:"https://storyuniverse.fandom.com/zh-tw/wiki/%E5%A4%9A%E9%87%8C%E5%AE%89%C2%B7%E5%BA%AB%E8%9D%A6"}}, {_id:88, properties:{gender:"生理男性", categories:"人類", title:"布羅迪·庫蝦"}}, {_id:89, properties:{gender:"生理男性", categories:"人類", title:"大衛·庫蝦"}}, {_id:90, properties:{gender:"生理男性", categories:"人類", title:"哈利·宿笍", url:"https://storyuniverse.fandom.com/zh-tw/wiki/%E5%93%88%E5%88%A9%C2%B7%E5%AE%BF%E7%AC%8D"}}, {_id:91, properties:{gender:"生理男性", categories:"人類", title:"史丹利·宿笍"}}, {_id:92, properties:{gender:"生理男性", categories:"人類", title:"傑克·宿笍"}}, {_id:93, properties:{gender:"生理男性", categories:"人類", title:"謝爾蓋·笞尼", url:"https://storyuniverse.fandom.com/zh-tw/wiki/%E8%AC%9D%E7%88%BE%E8%93%8B%C2%B7%E7%AC%9E%E5%B0%BC"}}, {_id:94, properties:{gender:"生理男性", categories:"人類", title:"迦勒·笞尼"}}, {_id:95, properties:{gender:"生理男性", categories:"人類", title:"肖恩·笞尼"}}, {_id:96, properties:{gender:"生理女性", categories:"人類", title:"艾琳·西洛", url:"https://storyuniverse.fandom.com/zh-tw/wiki/%E8%89%BE%E7%90%B3%EF%BC%8E%E8%A5%BF%E6%B4%9B"}}, {_id:97, properties:{gender:"生理女性", categories:"人類", title:"凱莉·西洛", url:"https://storyuniverse.fandom.com/zh-tw/wiki/%E5%87%B1%E8%8E%89%EF%BC%8E%E8%A5%BF%E6%B4%9B"}}, {_id:98, properties:{gender:"生理女性", categories:"人類", title:"奧莉維亞·西洛"}}, {_id:99, properties:{gender:"生理男性", categories:"人類", title:"山謬爾·西洛", url:"https://storyuniverse.fandom.com/zh-tw/wiki/%E5%B1%B1%E8%AC%AC%E7%88%BE%EF%BC%8E%E8%A5%BF%E6%B4%9B"}}, {_id:100, properties:{gender:"生理男性", categories:"人類", title:"斯特凡·西洛"}}, {_id:101, properties:{gender:"生理男性", categories:"人類", title:"雷吉·西洛"}}] AS row
CREATE (n:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row._id}) SET n += row.properties SET n:人類;
UNWIND [{_id:102, properties:{gender:"生理女性", categories:"人類", title:"娜丁·亞歷山大", url:"https://storyuniverse.fandom.com/zh-tw/wiki/%E5%A8%9C%E4%B8%81%EF%BC%8E%E4%BA%9E%E6%AD%B7%E5%B1%B1%E5%A4%A7"}}, {_id:103, properties:{gender:"生理女性", categories:"人類", title:"米凱拉·亞歷山大"}}, {_id:104, properties:{gender:"生理男性", categories:"人類", title:"馬汀·亞歷山大", url:"https://storyuniverse.fandom.com/zh-tw/wiki/%E9%A6%AC%E6%B1%80%EF%BC%8E%E4%BA%9E%E6%AD%B7%E5%B1%B1%E5%A4%A7"}}, {_id:105, properties:{gender:"生理男性", categories:"人類", title:"皮埃爾·亞歷山大"}}, {_id:106, properties:{gender:"生理男性", categories:"人類", title:"特里斯坦·亞歷山大"}}, {_id:107, properties:{gender:"生理女性", categories:"人類", title:"娜塔莉·拉斯莫丁", url:"https://storyuniverse.fandom.com/zh-tw/wiki/%E5%A8%9C%E5%A1%94%E8%8E%89%C2%B7%E6%8B%89%E6%96%AF%E8%8E%AB%E4%B8%81"}}, {_id:108, properties:{gender:"生理女性", categories:"人類", title:"米里亞姆·拉斯莫丁"}}, {_id:109, properties:{gender:"生理男性", categories:"人類", title:"海登·拉斯莫丁", url:"https://storyuniverse.fandom.com/zh-tw/wiki/%E6%B5%B7%E7%99%BB%C2%B7%E6%8B%89%E6%96%AF%E8%8E%AB%E4%B8%81"}}, {_id:110, properties:{gender:"生理男性", categories:"人類", title:"迪倫·拉斯莫丁", url:"https://storyuniverse.fandom.com/zh-tw/wiki/%E8%BF%AA%E5%80%AB%C2%B7%E6%8B%89%E6%96%AF%E8%8E%AB%E4%B8%81"}}, {_id:111, properties:{gender:"生理男性", categories:"人類", title:"阿爾弗雷多·拉斯莫丁"}}] AS row
CREATE (n:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row._id}) SET n += row.properties SET n:人類;
UNWIND [{_id:126, properties:{categories:"沒人擁有的區域", title:"蓮庫", url:"https://storyuniverse.fandom.com/zh-tw/wiki/%E8%93%AE%E5%BA%AB"}}, {_id:127, properties:{categories:"沒人擁有的區域", title:"蘭韋爾", url:"https://storyuniverse.fandom.com/zh-tw/wiki/%E8%98%AD%E9%9F%8B%E7%88%BE"}}] AS row
CREATE (n:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row._id}) SET n += row.properties SET n:沒人擁有的區域;
UNWIND [{start: {_id:2}, end: {_id:1}, properties:{}}, {start: {_id:3}, end: {_id:1}, properties:{}}, {start: {_id:5}, end: {_id:4}, properties:{}}, {start: {_id:6}, end: {_id:4}, properties:{}}, {start: {_id:7}, end: {_id:0}, properties:{}}, {start: {_id:8}, end: {_id:0}, properties:{}}, {start: {_id:9}, end: {_id:0}, properties:{}}] AS row
MATCH (start:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.start._id})
MATCH (end:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.end._id})
CREATE (start)-[r:subClassOf]->(end) SET r += row.properties;
UNWIND [{start: {_id:12}, end: {_id:135}, properties:{}}] AS row
MATCH (start:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.start._id})
MATCH (end:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.end._id})
CREATE (start)-[r:Have]->(end) SET r += row.properties;
UNWIND [{start: {_id:135}, end: {_id:96}, properties:{}}] AS row
MATCH (start:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.start._id})
MATCH (end:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.end._id})
CREATE (start)-[r:Raised_By]->(end) SET r += row.properties;
UNWIND [{start: {_id:126}, end: {_id:2}, properties:{}}, {start: {_id:127}, end: {_id:2}, properties:{}}] AS row
MATCH (start:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.start._id})
MATCH (end:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.end._id})
CREATE (start)-[r:ObjectOneOf]->(end) SET r += row.properties;
UNWIND [{start: {_id:15}, end: {_id:5}, properties:{}}, {start: {_id:16}, end: {_id:5}, properties:{}}, {start: {_id:17}, end: {_id:5}, properties:{}}, {start: {_id:18}, end: {_id:5}, properties:{}}, {start: {_id:19}, end: {_id:5}, properties:{}}, {start: {_id:20}, end: {_id:5}, properties:{}}, {start: {_id:21}, end: {_id:5}, properties:{}}, {start: {_id:22}, end: {_id:5}, properties:{}}, {start: {_id:23}, end: {_id:5}, properties:{}}, {start: {_id:24}, end: {_id:5}, properties:{}}, {start: {_id:25}, end: {_id:5}, properties:{}}, {start: {_id:26}, end: {_id:5}, properties:{}}, {start: {_id:27}, end: {_id:5}, properties:{}}, {start: {_id:35}, end: {_id:5}, properties:{}}, {start: {_id:36}, end: {_id:5}, properties:{}}, {start: {_id:37}, end: {_id:5}, properties:{}}, {start: {_id:38}, end: {_id:5}, properties:{}}, {start: {_id:39}, end: {_id:5}, properties:{}}, {start: {_id:40}, end: {_id:5}, properties:{}}, {start: {_id:41}, end: {_id:5}, properties:{}}] AS row
MATCH (start:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.start._id})
MATCH (end:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.end._id})
CREATE (start)-[r:ObjectOneOf]->(end) SET r += row.properties;
UNWIND [{start: {_id:42}, end: {_id:5}, properties:{}}, {start: {_id:43}, end: {_id:5}, properties:{}}, {start: {_id:44}, end: {_id:5}, properties:{}}, {start: {_id:45}, end: {_id:5}, properties:{}}, {start: {_id:46}, end: {_id:5}, properties:{}}, {start: {_id:47}, end: {_id:5}, properties:{}}, {start: {_id:48}, end: {_id:5}, properties:{}}, {start: {_id:49}, end: {_id:5}, properties:{}}, {start: {_id:50}, end: {_id:5}, properties:{}}, {start: {_id:51}, end: {_id:5}, properties:{}}, {start: {_id:52}, end: {_id:5}, properties:{}}, {start: {_id:53}, end: {_id:5}, properties:{}}, {start: {_id:54}, end: {_id:5}, properties:{}}, {start: {_id:55}, end: {_id:5}, properties:{}}, {start: {_id:56}, end: {_id:5}, properties:{}}, {start: {_id:57}, end: {_id:5}, properties:{}}, {start: {_id:58}, end: {_id:5}, properties:{}}, {start: {_id:59}, end: {_id:5}, properties:{}}, {start: {_id:60}, end: {_id:5}, properties:{}}, {start: {_id:61}, end: {_id:5}, properties:{}}] AS row
MATCH (start:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.start._id})
MATCH (end:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.end._id})
CREATE (start)-[r:ObjectOneOf]->(end) SET r += row.properties;
UNWIND [{start: {_id:62}, end: {_id:5}, properties:{}}, {start: {_id:63}, end: {_id:5}, properties:{}}, {start: {_id:64}, end: {_id:5}, properties:{}}, {start: {_id:65}, end: {_id:5}, properties:{}}, {start: {_id:66}, end: {_id:5}, properties:{}}, {start: {_id:67}, end: {_id:5}, properties:{}}, {start: {_id:68}, end: {_id:5}, properties:{}}, {start: {_id:69}, end: {_id:5}, properties:{}}, {start: {_id:70}, end: {_id:5}, properties:{}}, {start: {_id:71}, end: {_id:5}, properties:{}}, {start: {_id:72}, end: {_id:5}, properties:{}}, {start: {_id:73}, end: {_id:5}, properties:{}}, {start: {_id:74}, end: {_id:5}, properties:{}}, {start: {_id:75}, end: {_id:5}, properties:{}}, {start: {_id:76}, end: {_id:5}, properties:{}}, {start: {_id:77}, end: {_id:5}, properties:{}}, {start: {_id:78}, end: {_id:5}, properties:{}}, {start: {_id:79}, end: {_id:5}, properties:{}}, {start: {_id:80}, end: {_id:5}, properties:{}}, {start: {_id:81}, end: {_id:5}, properties:{}}] AS row
MATCH (start:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.start._id})
MATCH (end:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.end._id})
CREATE (start)-[r:ObjectOneOf]->(end) SET r += row.properties;
UNWIND [{start: {_id:82}, end: {_id:5}, properties:{}}, {start: {_id:83}, end: {_id:5}, properties:{}}, {start: {_id:84}, end: {_id:5}, properties:{}}, {start: {_id:85}, end: {_id:5}, properties:{}}, {start: {_id:86}, end: {_id:5}, properties:{}}, {start: {_id:87}, end: {_id:5}, properties:{}}, {start: {_id:88}, end: {_id:5}, properties:{}}, {start: {_id:89}, end: {_id:5}, properties:{}}, {start: {_id:90}, end: {_id:5}, properties:{}}, {start: {_id:91}, end: {_id:5}, properties:{}}, {start: {_id:92}, end: {_id:5}, properties:{}}, {start: {_id:93}, end: {_id:5}, properties:{}}, {start: {_id:94}, end: {_id:5}, properties:{}}, {start: {_id:95}, end: {_id:5}, properties:{}}, {start: {_id:96}, end: {_id:5}, properties:{}}, {start: {_id:97}, end: {_id:5}, properties:{}}, {start: {_id:98}, end: {_id:5}, properties:{}}, {start: {_id:99}, end: {_id:5}, properties:{}}, {start: {_id:100}, end: {_id:5}, properties:{}}, {start: {_id:101}, end: {_id:5}, properties:{}}] AS row
MATCH (start:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.start._id})
MATCH (end:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.end._id})
CREATE (start)-[r:ObjectOneOf]->(end) SET r += row.properties;
UNWIND [{start: {_id:102}, end: {_id:5}, properties:{}}, {start: {_id:103}, end: {_id:5}, properties:{}}, {start: {_id:104}, end: {_id:5}, properties:{}}, {start: {_id:105}, end: {_id:5}, properties:{}}, {start: {_id:106}, end: {_id:5}, properties:{}}, {start: {_id:107}, end: {_id:5}, properties:{}}, {start: {_id:108}, end: {_id:5}, properties:{}}, {start: {_id:109}, end: {_id:5}, properties:{}}, {start: {_id:110}, end: {_id:5}, properties:{}}, {start: {_id:111}, end: {_id:5}, properties:{}}] AS row
MATCH (start:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.start._id})
MATCH (end:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.end._id})
CREATE (start)-[r:ObjectOneOf]->(end) SET r += row.properties;
UNWIND [{start: {_id:112}, end: {_id:3}, properties:{}}, {start: {_id:113}, end: {_id:3}, properties:{}}, {start: {_id:114}, end: {_id:3}, properties:{}}, {start: {_id:115}, end: {_id:3}, properties:{}}, {start: {_id:116}, end: {_id:3}, properties:{}}, {start: {_id:117}, end: {_id:3}, properties:{}}, {start: {_id:118}, end: {_id:3}, properties:{}}, {start: {_id:119}, end: {_id:3}, properties:{}}, {start: {_id:120}, end: {_id:3}, properties:{}}, {start: {_id:121}, end: {_id:3}, properties:{}}, {start: {_id:122}, end: {_id:3}, properties:{}}, {start: {_id:123}, end: {_id:3}, properties:{}}, {start: {_id:124}, end: {_id:3}, properties:{}}, {start: {_id:125}, end: {_id:3}, properties:{}}] AS row
MATCH (start:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.start._id})
MATCH (end:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.end._id})
CREATE (start)-[r:ObjectOneOf]->(end) SET r += row.properties;
UNWIND [{start: {_id:135}, end: {_id:6}, properties:{}}] AS row
MATCH (start:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.start._id})
MATCH (end:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.end._id})
CREATE (start)-[r:ObjectOneOf]->(end) SET r += row.properties;
UNWIND [{start: {_id:12}, end: {_id:96}, properties:{}}, {start: {_id:12}, end: {_id:97}, properties:{}}, {start: {_id:12}, end: {_id:98}, properties:{}}, {start: {_id:12}, end: {_id:99}, properties:{}}, {start: {_id:12}, end: {_id:100}, properties:{}}, {start: {_id:12}, end: {_id:101}, properties:{}}, {start: {_id:11}, end: {_id:102}, properties:{}}, {start: {_id:11}, end: {_id:103}, properties:{}}, {start: {_id:11}, end: {_id:104}, properties:{}}, {start: {_id:11}, end: {_id:105}, properties:{}}, {start: {_id:11}, end: {_id:106}, properties:{}}, {start: {_id:10}, end: {_id:107}, properties:{}}, {start: {_id:10}, end: {_id:108}, properties:{}}, {start: {_id:10}, end: {_id:109}, properties:{}}, {start: {_id:10}, end: {_id:110}, properties:{}}, {start: {_id:10}, end: {_id:111}, properties:{}}, {start: {_id:14}, end: {_id:42}, properties:{}}, {start: {_id:14}, end: {_id:43}, properties:{}}, {start: {_id:14}, end: {_id:44}, properties:{}}, {start: {_id:13}, end: {_id:45}, properties:{}}] AS row
MATCH (start:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.start._id})
MATCH (end:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.end._id})
CREATE (start)-[r:Have]->(end) SET r += row.properties;
UNWIND [{start: {_id:13}, end: {_id:46}, properties:{}}, {start: {_id:13}, end: {_id:47}, properties:{}}, {start: {_id:13}, end: {_id:48}, properties:{}}, {start: {_id:131}, end: {_id:58}, properties:{}}, {start: {_id:131}, end: {_id:59}, properties:{}}, {start: {_id:14}, end: {_id:79}, properties:{}}, {start: {_id:14}, end: {_id:80}, properties:{}}, {start: {_id:14}, end: {_id:81}, properties:{}}, {start: {_id:13}, end: {_id:82}, properties:{}}, {start: {_id:13}, end: {_id:83}, properties:{}}, {start: {_id:131}, end: {_id:93}, properties:{}}, {start: {_id:131}, end: {_id:94}, properties:{}}, {start: {_id:131}, end: {_id:95}, properties:{}}] AS row
MATCH (start:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.start._id})
MATCH (end:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.end._id})
CREATE (start)-[r:Have]->(end) SET r += row.properties;
UNWIND [{start: {_id:132}, end: {_id:8}, properties:{}}, {start: {_id:133}, end: {_id:8}, properties:{}}, {start: {_id:134}, end: {_id:8}, properties:{}}] AS row
MATCH (start:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.start._id})
MATCH (end:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.end._id})
CREATE (start)-[r:ObjectOneOf]->(end) SET r += row.properties;
UNWIND [{start: {_id:15}, end: {_id:126}, properties:{}}, {start: {_id:16}, end: {_id:127}, properties:{}}, {start: {_id:60}, end: {_id:127}, properties:{}}, {start: {_id:61}, end: {_id:126}, properties:{}}, {start: {_id:19}, end: {_id:126}, properties:{}}] AS row
MATCH (start:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.start._id})
MATCH (end:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.end._id})
CREATE (start)-[r:Lived_In]->(end) SET r += row.properties;
UNWIND [{start: {_id:10}, end: {_id:7}, properties:{}}, {start: {_id:11}, end: {_id:7}, properties:{}}, {start: {_id:12}, end: {_id:7}, properties:{}}, {start: {_id:13}, end: {_id:7}, properties:{}}, {start: {_id:14}, end: {_id:7}, properties:{}}, {start: {_id:131}, end: {_id:7}, properties:{}}] AS row
MATCH (start:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.start._id})
MATCH (end:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.end._id})
CREATE (start)-[r:ObjectOneOf]->(end) SET r += row.properties;
UNWIND [{start: {_id:128}, end: {_id:9}, properties:{}}, {start: {_id:129}, end: {_id:9}, properties:{}}, {start: {_id:130}, end: {_id:9}, properties:{}}] AS row
MATCH (start:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.start._id})
MATCH (end:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.end._id})
CREATE (start)-[r:ObjectOneOf]->(end) SET r += row.properties;
UNWIND [{start: {_id:116}, end: {_id:124}, properties:{}}, {start: {_id:125}, end: {_id:123}, properties:{}}, {start: {_id:116}, end: {_id:119}, properties:{}}, {start: {_id:125}, end: {_id:120}, properties:{}}, {start: {_id:116}, end: {_id:121}, properties:{}}, {start: {_id:115}, end: {_id:112}, properties:{}}, {start: {_id:115}, end: {_id:113}, properties:{}}, {start: {_id:115}, end: {_id:114}, properties:{}}] AS row
MATCH (start:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.start._id})
MATCH (end:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.end._id})
CREATE (start)-[r:Consists_Of]->(end) SET r += row.properties;
UNWIND [{start: {_id:133}, end: {_id:49}, properties:{}}, {start: {_id:133}, end: {_id:50}, properties:{}}, {start: {_id:133}, end: {_id:51}, properties:{}}, {start: {_id:132}, end: {_id:52}, properties:{}}, {start: {_id:132}, end: {_id:53}, properties:{}}, {start: {_id:132}, end: {_id:54}, properties:{}}, {start: {_id:134}, end: {_id:55}, properties:{}}, {start: {_id:134}, end: {_id:56}, properties:{}}, {start: {_id:134}, end: {_id:57}, properties:{}}, {start: {_id:133}, end: {_id:84}, properties:{}}, {start: {_id:133}, end: {_id:85}, properties:{}}, {start: {_id:133}, end: {_id:86}, properties:{}}, {start: {_id:132}, end: {_id:87}, properties:{}}, {start: {_id:132}, end: {_id:88}, properties:{}}, {start: {_id:132}, end: {_id:89}, properties:{}}, {start: {_id:134}, end: {_id:90}, properties:{}}, {start: {_id:134}, end: {_id:91}, properties:{}}, {start: {_id:134}, end: {_id:92}, properties:{}}] AS row
MATCH (start:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.start._id})
MATCH (end:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.end._id})
CREATE (start)-[r:Have]->(end) SET r += row.properties;
UNWIND [{start: {_id:17}, end: {_id:120}, properties:{}}, {start: {_id:63}, end: {_id:120}, properties:{}}, {start: {_id:20}, end: {_id:119}, properties:{}}, {start: {_id:21}, end: {_id:119}, properties:{}}, {start: {_id:22}, end: {_id:114}, properties:{}}, {start: {_id:23}, end: {_id:124}, properties:{}}, {start: {_id:24}, end: {_id:124}, properties:{}}, {start: {_id:25}, end: {_id:114}, properties:{}}, {start: {_id:26}, end: {_id:121}, properties:{}}, {start: {_id:27}, end: {_id:121}, properties:{}}, {start: {_id:35}, end: {_id:121}, properties:{}}, {start: {_id:36}, end: {_id:112}, properties:{}}, {start: {_id:37}, end: {_id:112}, properties:{}}, {start: {_id:38}, end: {_id:113}, properties:{}}, {start: {_id:39}, end: {_id:114}, properties:{}}, {start: {_id:40}, end: {_id:120}, properties:{}}, {start: {_id:64}, end: {_id:124}, properties:{}}, {start: {_id:65}, end: {_id:124}, properties:{}}, {start: {_id:66}, end: {_id:121}, properties:{}}, {start: {_id:67}, end: {_id:121}, properties:{}}] AS row
MATCH (start:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.start._id})
MATCH (end:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.end._id})
CREATE (start)-[r:Lived_In]->(end) SET r += row.properties;
UNWIND [{start: {_id:68}, end: {_id:114}, properties:{}}, {start: {_id:69}, end: {_id:114}, properties:{}}, {start: {_id:70}, end: {_id:119}, properties:{}}, {start: {_id:71}, end: {_id:119}, properties:{}}, {start: {_id:72}, end: {_id:112}, properties:{}}, {start: {_id:73}, end: {_id:112}, properties:{}}, {start: {_id:74}, end: {_id:112}, properties:{}}, {start: {_id:75}, end: {_id:113}, properties:{}}, {start: {_id:76}, end: {_id:114}, properties:{}}, {start: {_id:78}, end: {_id:120}, properties:{}}] AS row
MATCH (start:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.start._id})
MATCH (end:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.end._id})
CREATE (start)-[r:Lived_In]->(end) SET r += row.properties;
MATCH (n:`UNIQUE IMPORT LABEL`)  WITH n LIMIT 20000 REMOVE n:`UNIQUE IMPORT LABEL` REMOVE n.`UNIQUE IMPORT ID`;
DROP CONSTRAINT ON (node:`UNIQUE IMPORT LABEL`) ASSERT (node.`UNIQUE IMPORT ID`) IS UNIQUE;
